### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rafaelklaessen** [rafaelklaessen/vx-components-react#1]
- [x] `Toggle`
- [x] `Dialog`
- [x] `GradientCard`
- [x] `Tabs`
- [x] Other components?
- [x] Better docs for `theme`
- [x] Docs for color (& style) utils?
- [x] Fancier README
- [x] `LoadingSpinner` (fullscreen & non-fullscreen)
